name: Call Render Tee Time Check

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch:       # allows manual trigger from GitHub UI

jobs:
  call_render_check:
    runs-on: ubuntu-latest

    steps:
      - name: Random delay up to 15 minutes
        run: sleep $(( RANDOM % 900 ))  # random sleep 0-900 seconds

      - name: Call Render /run_check endpoint
        run: curl -s https://golfnow-1.onrender.com/run_check

